### ISSUE TITLE
How to integrate with sequelize

### ISSUE THREAD

**Issue by alexsad** [WebReflection/dblite#42]
How to integrate with sequelize ? Its is easy ?

**Comment by WebReflection** [comment]
I'm afraid I don't have time to implement a sequelize dialect. You might want to try to fork them, recycle basically everything they do with the sqlite dialect but use dblite instead of the sqlite module when it comes to execute raws queries. They sanitize pretty much everything so that at the end of the day all you need to do is create a db and execute the created query string through
```js
db.query('SELECT * FROM table', function(err, rows) {
  err ? reject(err) : resolve(rows);
});
```
